const express = require('express')
const auth = require('./auth/router/auth')
const users = require('./users/users.router')
const empresas = require('./empresas/empresas.router')
const areas = require('./areas/areas.router')
const sucursales = require('./sucursales/sucursales.router')
const sectores = require('./sectores/sectores.router')
const puestos = require('./puestos/puestos.router')
const sindicatos = require('./sindicatos/sindicatos.router')
const categorias = require('./categorias/categorias.router')
const colaboradores_puestos = require('./colaborador_puestos/colaboradores_puestos.router')
const estados_civiles = require('./estados_civiles/estados_civiles.router')
const sexos = require('./sexos/sexos.router')
const relaciones_familiares = require('./relaciones_familiares/relaciones_familiares.router')

const router = express.Router()

router.use('/auth', auth)
router.use('/users', users)
router.use('/empresas', empresas)
router.use('/areas', areas)
router.use('/sucursales', sucursales)
router.use('/sectores', sectores)
router.use('/puestos', puestos)
router.use('/sindicatos', sindicatos)
router.use('/categorias', categorias)
router.use('/colaboradorpuesto', colaboradores_puestos)
router.use('/estadosciviles', estados_civiles)
router.use('/sexos', sexos)
router.use('/relacionesfamiliares', relaciones_familiares)

module.exports = router